### PR TITLE
performance: import traversal

### PR DESCRIPTION
**Pull request by 43081j**
analysis takes an incredible amount of time in some of my repos, so i have profiled it and tested it today...

almost all the CPU time is lost to traversal of the dependency graph, i.e. simply the massive amount of recursive calls in `visitDependencies` reach an unreasonable level.

what do you think of this?

the change is to **only visit imported modules which we imported directly, not from external libraries**.

im making these assumptions:

* web-analyzer has already parsed direct imports by this point i imagine, so we already know what elements (and their properties etc) a direct import provides
* it is bad practice to rely on deeply nested imports out of your control to expose an element, you should import it directly

given these two assumptions, all imported elements must be direct imports.

Quick timings in one of my repos:

Before:

```bash
real 2m6.236s
user 2m11.438s
sys 0m3.328s
```

after:

```bash
real 0m13.535s
user 0m18.063s
sys 0m2.031s
```

Same number of errors and warnings came back in all the repos i tried.

cc @runem

### CODE REVIEW

**Comment by runem** [comment]
Wow, great catch!

One concern I have with this change is that it's no longer possible to depend on barrel modules from a library. I agree that it's bad practice to rely on deeply nested imports from an external library, but barrel modules can be used as a controlled and useful way of exposing elements.

Here's and example of how we do it in my company:

**./src/my-element.ts**
```typescript
import "@ideanote/atoms/lib/button";
```

**./node_modules/@ideanote/atoms/lib/button/index.d.ts**
```typescript
export * from "./at-button";
```

**./node_modules/@ideanote/atoms/lib/button/at-button.d.ts**
```typescript
...

declare global {
    interface HTMLElementTagNameMap {
        "at-button": AtButton;
    }
}
```

This change would have us to change all of the library imports to this instead:

```typescript
import "@ideanote/atoms/lib/button/at-button";
```

If possible I would really love to find a performant solution where this kind of pattern become possible. For example by introducing caching, only following external exports X levels deep, or only following the chain of exports in external modules consisting purely of exports :-)

**Comment by 43081j** [comment]
Simply changing this to use a max depth would solve your problem there and defaulting to 2 levels deep (i.e. direct imports and their direct imports).

I will update it if that works for you

**Comment by 43081j** [comment]
something like what i just pushed but maybe configurable some place

**Comment by runem** [comment]
I think it looks like a fine solution :blush: I still haven't built the functionality to configure rules, but I expect it will be the same as [eslint](https://eslint.org/docs/user-guide/configuring#using-configuration-files). 

One thing: the newly added `.editorconfig`-file crashes `prettier` because it tries to reformat it on `npm run prettier:write`, so we would either have to add an entry to `.prettierignore` or `.gitignore`. If you want to keep the file I would love it to look something like this:

```
root = true

[*]
charset = utf-8
indent_size = 2
indent_style = tab
```

**Comment by 43081j** [comment]
it'd be good to keep it since it means there's no risk of people accidentally introducing mixed formatting.

the sources i've seen so far have been 1 tab deep, too, are you sure indent_size should be 2?

**Comment by runem** [comment]
Sorry, I was confusing `indent_size` with `tab_width`. I would prefer a `tab_width` of 2 :-)

**Comment by 43081j** [comment]
there you go i updated it

**Comment by runem** [comment]
Great, thanks! I'll merge now

**Pull request merged**
