### PR TITLE
Add the ability to emit index entries.

### PR DESCRIPTION
**Pull request by bicknellr**
This is an updated version of #37.

### CODE REVIEW

**Comment by bicknellr** [comment]
cc @rictic

**Review by rictic — APPROVED** [review]
Excellent test suite!

**Comment by bicknellr** [comment]
I noticed there were a few places in the tests that used `.js` in the test file names when they should technically be `.ts`, so I updated those.

**Comment by bicknellr** [comment]
Oh, I don't have merge permissions for this repo.

**Comment by bicknellr** [comment]
I'm going to add a change log entry also.

**Comment by bicknellr** [comment]
Added.

**Pull request merged**
